/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "verify.h"

bool_t
xdr_str_t (XDR *xdrs, str_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 255))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_my_struct (XDR *xdrs, my_struct *objp)
{
	register int32_t *buf;

	 if (!xdr_str_t (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}
